### ISSUE TITLE
newbie - however API feels inconsistent - would some refactoring improve consistency?

### ISSUE THREAD

**Issue by woodmawa** [EasyRules/easyrules#31]
I have been having a play with easyRules for a project - i like the simplicity of the model (havnet volume tested for performance - this is more about the API

I've been looking at easyRules and springboot.  however i cant quite reconcile the model differences between jmxRuleEngine and ordinary ruleEngine.  Why are there tow class types, in my head they better as configuration -RuleEngine (jmxEnabled true/false) 

also the BasicRule class (evaluate & execute) is defferent from using @rule to convert a pojo into spring bean (condition/action/action etc ) 

when i tried to add a Spring @rule class to ruleEngine.addRule it wouldn't accept it, i had to get a rulesEngine from the spring context (after config ) and added spring rule to that engine and that worked - but that meant i had two engines to play with 

as a new user of easyRules i found this a little perplexing and inconsistent, and forced you make choices for one mode or the other (extend BasicRule, or go for the Spring bean model, or jmx, not jmx ) .  

I managed to get various samples up and running but the usage was inconsistent and I felt could be simplified and harmonised to remove these differences and make the developer 'experience' easier and more consistent.

I admit that i haven't coded as a developer 'for real' for many years now - so apologies if i have not got the best way to use this, but just wanted to plant a seed of thought for consideration.  I'll have another little play - i'm using groovy so it maybe i can see if its possible to 'hide' some of the mechanical differences and see what that looks like

**Comment by benas** [comment]
Hi,

Thank you for trying out Easy Rules!

> however i cant quite reconcile the model differences between jmxRuleEngine and ordinary ruleEngine. Why are there tow class types, in my head they better as configuration -RuleEngine (jmxEnabled true/false)

This is inconsistent, you should register Jmx and non Jmx rules the same way, it is the role of the framework to make this transparent to the user. I am planning to fix that in the next release.

> also the BasicRule class (evaluate & execute) is defferent from using @rule to convert a pojo into spring bean (condition/action/action etc )

As of version 1.x, there was a big inconsistency in the framework: annotated rules and rules extending the `BasicRule` class or implementing the `Rule` interface were registered using two different types of engines. In order to make both approaches consistent, we decided to make annotated POJOs implement the `Rule` interface using proxies (see issue #12 for more details). That said, both approaches are different indeed, but is this really problematic? You have the choice between two options and the framework offers you the flexibility to choose the one that better fits your needs

> when i tried to add a Spring @rule class to ruleEngine.addRule it wouldn't accept it, i had to get a rulesEngine from the spring context (after config ) and added spring rule to that engine and that worked - but that meant i had two engines to play with

I'm not sure I understand this point, can you give me an example please? If you believe this is a bug, please open a separate issue.

> as a new user of easyRules i found this a little perplexing and inconsistent, and forced you make choices for one mode or the other (extend BasicRule, or go for the Spring bean model, or jmx, not jmx ) .

So let me summarise, there are basically two points:

* Extend `BasicRule`/ Implement `Rule` vs Annotating a POJO: the framework offers you two different ways to implement your business rule, it is up to you to choose the best choice that fits your needs

* Jmx managed rules vs Non Jmx managed rule: As said before, I do agree with you, this is inconsistent and I'm planning to improve it in the upcoming release.

> would some refactoring improve consistency?

Sure, Easy Rules can be improved in many ways, you are welcome to improve the design or implementation!

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi,

> Jmx managed rules vs Non Jmx managed rule: As said before, I do agree with you, this is inconsistent and I'm planning to improve it in the upcoming release.

I'm struggling to find a clean way to implement JMX managed rules in a compatible way with android. Hence, I've decided to deprecate the feature (see issue #47)

> when i tried to add a Spring @rule class to ruleEngine.addRule it wouldn't accept it, i had to get a rulesEngine from the spring context (after config ) and added spring rule to that engine and that worked - but that meant i had two engines to play with

I'm not sure I understand this point, can you give me an example please?

Kind regards
Mahmoud

**Comment by woodmawa** [comment]
Mahmoud, 
sorry been distracted at work and havent had the spare time to address this realistically 
one thing i was looking at the was the java std api for rules (JSR 94) - 
havent studied the android issue so cant comment 
still need to have a proper think about how to  wrap what you have done - so not forgotten just distracted - will try and restart shortly
Will 
----Original message----
From : notifications@github.com
Date : 19/08/2016 - 13:27 (GMTST)
To : easyrules@noreply.github.com
Cc : will.woodman@btinternet.com, author@noreply.github.com
Subject : Re: [EasyRules/easyrules] newbie - however API feels inconsistent - would some refactoring improve consistency? (#31)
Hi,
Jmx managed rules vs Non Jmx managed rule: As said before, I do agree with you, this is inconsistent and I'm planning to improve it in the upcoming release.
I'm struggling to find a clean way to implement JMX managed rules in a compatible way with android. Hence, I've decided to deprecate the feature (see issue #47)
when i tried to add a Spring @rule class to ruleEngine.addRule it wouldn't accept it, i had to get a rulesEngine from the spring context (after config ) and added spring rule to that engine and that worked - but that meant i had two engines to play with
I'm not sure I understand this point, can you give me an example please?
Kind regards
Mahmoud
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
  
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/EasyRules/easyrules","title":"EasyRules/easyrules","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/EasyRules/easyrules"}},"updates":{"snippets":[{"icon":"PERSON","message":"@benas in #31: Hi,\r\n\r\n\u003e Jmx managed rules vs Non Jmx managed rule: As said before, I do agree with you, this is inconsistent and I'm planning to improve it in the upcoming release.\r\n\r\nI'm struggling to find a clean way to implement JMX managed rules in a compatible way with android. Hence, I've decided to deprecate the feature (see issue #47)\r\n\r\n\u003e when i tried to add a Spring @rule class to ruleEngine.addRule it wouldn't accept it, i had to get a rulesEngine from the spring context (after config ) and added spring rule to that engine and that worked - but that meant i had two engines to play with\r\n\r\nI'm not sure I understand this point, can you give me an example please?\r\n\r\nKind regards\r\nMahmoud"}],"action":{"name":"View Issue","url":"https://github.com/EasyRules/easyrules/issues/31#issuecomment-241005111"}}}

**Comment by benas** [comment]
Hi,

Implementing JSR 94 has been considered since the early stages of Easy Rules but has never been a first order concern. This will require a major API change, I may consider it in the next major release v3. 

I'm closing this issue for now, if you have any other question, I'll be happy to help.

Kind regards
Mahmoud
