### ISSUE TITLE
Composite Rules

### ISSUE THREAD

**Issue by raksha-rao** [EasyRules/easyrules#45]
While using composite rules to add my rules, i don't have the flexibility of using annotations. In this case, i realised the system expects Basic rule to be extended. Is there any specific reason for this?

**Comment by benas** [comment]
Hi, no reason. The `addRule` method of `CompositeRule` should take an object which can be an annotated POJO, not only a `Rule`. I'll make this change for next release. Keep tuned.

**Comment by raksha-rao** [comment]
Cool. Thank you.

**Comment by benas** [comment]
Hi, this has been fixed in #41 . I've already updated the API to be able to use annotated POJOs with composite rules. It seems that [it works as expected](https://github.com/EasyRules/easyrules/issues/41#issuecomment-224083434), but can you give it a try with version 2.3.0-SNAPSHOT? two heads are better than one :smile:

**Comment by benas** [comment]
@raksha-rao I'm preparing to release v2.3 with this fix. If you still have any issue, please reopen the issue.

Kind regards
Mahmoud

**Comment by raksha-rao** [comment]
@benas  I was using the previous version which is why I came across the discrepancy. My mistake. Thank you.
