### ISSUE TITLE
Why bother with Spring

### ISSUE THREAD

**Issue by ssozonoff** [EasyRules/easyrules#50]
Hi,

Considering as a new RulesEngine instance is needed + a new Rule instance for every Rule which needs to be set on the RulesEngine to maintain state I am not clear what value Spring brings to any of this...... 

Take for example a REST request which hits the server and trigger a bunch of Rules.

For every request we will need at least one or more Rules on which we set some sort of Object for the State. Then we need a fresh RulesEngine to which set the Rules. We probably have to pass in the HttpReponse object as well so that the Last rule to be fired can respond back.....

I dont see any value in using @SpringRule or the RulesEngineFactoryBean.... what am I missing?

Thanks

**Comment by benas** [comment]
Hi, 

There are many advantages when you use Easy Rules with Spring:

* You can activate/deactivate rules without recompiling your app:

```xml
<bean id="rulesEngine" class="org.easyrules.spring.RulesEngineFactoryBean">
   <property name="rules">
            <list>
                <ref bean="rule1"/>
                <ref bean="rule2"/>
            </list>
     </property>
</bean>
```
For example, just comment "rule2" to deactivate this rule.

* You can reconfigure your rules without recompiling your app ( like the "legal age" in the [shop tutorial](http://www.easyrules.org/tutorials/shop-tutorial.html)) and probably at runtime (by refreshing the spring context)
* When your rule is annotated with `@SpringRule`, you can benefit from dependency injection. As in your example, you can inject the http request object in your rule. Without that, you have to do it manually
* If your rules engine and rules are managed by spring (and are prototype scoped, which is the case if you use the `RulesEngineFactoryBean` and `@SpringRule`), you only have to ask spring for a new rules engine instance and fire rules: `(RulesEngine) context.getBean("rulesEngine").fireRules();`. The instance you get is already configured and all rules are dependency-inject and registered in the rules engine. Without Spring, you have to create the rules engine instance, rules instances and register rules manually each time

Do you see?

Kind regards
Mahmoud

**Comment by benas** [comment]
@ssozonoff 

Do these points make sense?

**Comment by ssozonoff** [comment]
Yes. Thanks for this.

Serge

**Comment by benas** [comment]
Hi Serge,

Glad it helped!

> Take for example a REST request which hits the server and trigger a bunch of Rules.

There is an example like this in issue #16 that may also help.

Kind regards
Mahmoud

**Comment by oliv37** [comment]
Like @ssozonoff I don't see the benefits of using Easy Rules Spring unless you want to inject spring beans in your rules or if your rules are thread safe (that's means they don't use business object model)

Otherwise for each requests you will need fresh instances of the rules and a fresh instance of the engine, so the benefit of using spring is minor. If you use spring, you will have to call ctx.getBean( "ruleEngine" ) each time you want to retrieve the rule engine.
It will also take more time to run your tests as you will need to start the Spring Container before.

I tried another solution 

```
public abstract class AbstractRuleSet
{
	private RulesEngineBuilder builder;

	public AbstractRuleSet()
	{
		builder = aNewRulesEngine();
	}

        public AbstractRuleSet(RulesEngineBuilder builder)
	{
		this.builder = builder;
	}

	public RulesEngine build()
	{
		RulesEngine ruleEngine = builder.build();

		if ( getRulesToRegister() != null )
		{
			getRulesToRegister().stream().forEach( ruleEngine::registerRule );
		}

		return ruleEngine;
	}

        protected abstract List<? extends BasicRule> getRulesToRegister();

 }
```

Then I extend the **AbstractRuleSet** for each business feature of my application and I will just have to provide the rules in in the **getRulesToRegister** method.

**Comment by benas** [comment]
> Like @ssozonoff I don't see the benefits of using Easy Rules Spring unless you want to inject spring beans in your rules

Ok basically only point 3 is relevant to you. what about 1) and 2)? These are two strong arguments to use spring with easy rules. Do you agree?

> or if your rules are thread safe (that's means they don't use business object model)

Your rules are thread safe does not mean they don't use BOM. Your rules can be stateful and thread safe at the same time if you add synchronization, but I would not recommended this.

> Otherwise for each requests you will need fresh instances of the rules and a fresh instance of the engine

This is correct if you use easy rules in a web app. But as I said in #16, with v3 the engine will be stateless and only rules should be of scope request (since they are applied on each request).

> It will also take more time to run your tests as you will need to start the Spring Container before.

This is true for any app using spring ..

**Comment by oliv37** [comment]
> Ok basically only point 3 is relevant to you. what about 1) and 2)? These are two strong arguments to use easy rules with spring. Do you agree?

Yes these are strong arguments, in my case I don't need reconfigure the rules on runtime, I think I will not use easyrules-spring, it will be faster to test the app.
